### PR TITLE
add ability to mount any file that contains a filesystem

### PR DESCRIPTION
**Pull request by gila**
I'm writing a CSI plugin which, during testing, needs to mount files that contain a filesystem other then squashfs and ISO9660. 

I've made these changes that allow me to do so. Issuing the raw IOCTL even with mount flags set to empty (ie RW) is not sufficient as a follow-up ioclt (LOOP_SET_STATUS64) is needed.

Let me know what you think,

Thanks!

### CODE REVIEW

**Comment by mmstick** [comment]
I'll check it out. The only thing that really matters here is that it works.

**Comment by mmstick** [comment]
Everything looks good

**Comment by mmstick** [comment]
It will soon be available on Crates.io as version `1.2.0`

**Comment by gila** [comment]
Cool looking forward to it!

**Pull request merged**
